/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class validatorLib_ValidatorLib */

#ifndef _Included_validatorLib_ValidatorLib
#define _Included_validatorLib_ValidatorLib
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     validatorLib_ValidatorLib
	 * Method:    createValidator
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_validatorLib_ValidatorLib_createValidator
	(JNIEnv*, jobject);

	/*
	 * Class:     validatorLib_ValidatorLib
	 * Method:    destroyValidator
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_validatorLib_ValidatorLib_destroyValidator
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     validatorLib_ValidatorLib
	 * Method:    validate
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_validatorLib_ValidatorLib_validate
	(JNIEnv*, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
